version: "3.8"
services:

  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "25432:5432"
    volumes:
# Uncomment his for windows, but update your path to reflect where you want your database data stored
# Change only the "c:/gist604b_data" and leave the "postgres_data/data:/var/lib/postgresql/data" as is.
#      - c:/gist604b_data/postgres_data/data:/var/lib/postgresql/data
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8280:8080"
    volumes:
# Uncomment his for windows, but update your path to reflect where you want your geoserver data stored
# Change only the "c:/gist604b_data" and leave the "geoserver_data/data_dir:/opt/geoserver/data_dir" as is.
#      - c:/gist604b_data/geoserver_data/data_dir:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - SAMPLE_DATA=true

networks:
  default:
    external:
      name: gist604b
